<a href="https://colab.research.google.com/github/MukulRaj-704/Machine-Learning-Algos/blob/main/Linear%20Regression/LinearRegression_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
np.random.seed(42)
temp=np.random.rand(56,57)
temp2=np.random.uniform(50,100,20)

In [3]:
print(temp)
print(temp2)

[[0.37454012 0.95071431 0.73199394 ... 0.59789998 0.92187424 0.0884925 ]
 [0.19598286 0.04522729 0.32533033 ... 0.16122129 0.92969765 0.80812038]
 [0.63340376 0.87146059 0.80367208 ... 0.04077514 0.59089294 0.67756436]
 ...
 [0.43276688 0.68544388 0.33245616 ... 0.86609563 0.94673373 0.1059058 ]
 [0.15482861 0.94473626 0.73653523 ... 0.93271051 0.54425397 0.20028202]
 [0.61678361 0.74288149 0.73791739 ... 0.78929285 0.30779583 0.91378844]]
[97.64075085 66.3371271  67.72124744 75.28170767 97.05604063 93.81597166
 55.12839813 69.63653716 77.66855949 75.15662363 59.6931534  92.94083856
 83.84703915 91.89541874 92.93821397 87.41779268 71.96053006 80.52733775
 58.01827031 83.68227087]


In [4]:
np.random.rand(42)
temp=np.random.uniform(20,40,150).reshape(-1,1)
humidity = np.random.uniform(0,100,150).reshape(-1,1)
price = np.random.uniform(50,250,150).reshape(-1,1)

In [5]:
noise = np.random.normal(0, 15, 150).reshape(-1,1)

sales_mod = (
    200
    + 6 * temp
    - 0.8 * price
    - 0.6 * humidity
    + noise
)

sales_mod = np.clip(sales_mod, 0, None)


In [ ]:
print(sales_mod)

In [ ]:
print(f"temp = {temp} \n humidity= {humidity} \n price={price}")

In [8]:
X=np.hstack((temp,humidity,price))

In [33]:
ones=np.ones((X.shape[0],1))

In [11]:

X_b = np.hstack((ones,X))

In [13]:
X_b_T=X_b.T

In [14]:
B=np.linalg.inv((X_b_T@X_b))@(X_b_T@sales_mod)

In [15]:
print(B)

[[205.14330342]
 [  5.9406765 ]
 [ -0.54914927]
 [ -0.84779695]]


In [22]:
np.random.seed(42)
temp_test=np.random.uniform(20,40,30).reshape(-1,1)
humidity_test=np.random.uniform(0,100,30).reshape(-1,1)
price_test=np.random.uniform(50,250,30).reshape(-1,1)


In [25]:
noise_test = np.random.normal(0, 15, 30).reshape(-1,1)

sales_test = (
    200
    + 6 * temp_test
    - 0.8 * price_test
    - 0.6 * humidity_test
    + noise_test
)

In [26]:
sales_pred= (B[0]+B[1]*temp_test+B[2]*humidity_test+B[3]*price_test)

In [27]:
from sklearn.metrics import root_mean_squared_error

In [28]:
RMSE=root_mean_squared_error(sales_test,sales_pred)

In [29]:
print(RMSE)

16.14771071545326
