<a href="https://colab.research.google.com/github/MukulRaj-704/Machine-Learning-Algos/blob/main/Linear%20Regression/Multi_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

Creating a random dataset including the features tempreatre, humidity and price and analysing effect of these things on the sales of a ice cream

In [45]:
np.random.seed(1)
temp=np.random.uniform(20,40,150).reshape(-1,1)
humidity = np.random.uniform(0,100,150).reshape(-1,1)
price = np.random.uniform(50,250,150).reshape(-1,1)

In [46]:
print(temp)

[[28.34044009]
 [34.40648987]
 [20.0022875 ]
 [26.04665145]
 [22.93511782]
 [21.8467719 ]
 [23.72520423]
 [26.91121454]
 [27.93534948]
 [30.77633468]
 [28.38389029]
 [33.70439001]
 [24.08904499]
 [37.56234873]
 [20.54775186]
 [33.4093502 ]
 [28.34609605]
 [31.17379657]
 [22.80773877]
 [23.96202978]
 [36.01489137]
 [39.36523151]
 [26.26848356]
 [33.84645231]
 [37.52778305]
 [37.89213327]
 [21.70088423]
 [20.78109566]
 [23.39660839]
 [37.56285007]
 [21.96693668]
 [28.4221525 ]
 [39.1577906 ]
 [30.6633057 ]
 [33.83754228]
 [26.31031262]
 [33.73001855]
 [36.69251344]
 [20.36576555]
 [35.0028863 ]
 [39.77722178]
 [34.96331309]
 [25.60887984]
 [35.78558657]
 [22.06452013]
 [28.95787052]
 [38.17191006]
 [25.87228297]
 [25.75550677]
 [22.60057144]
 [20.38733916]
 [33.57671066]
 [24.23256232]
 [25.31093319]
 [29.83146319]
 [21.0672509 ]
 [31.48235211]
 [22.9345715 ]
 [31.78611074]
 [33.9951672 ]
 [22.04668858]
 [28.28111976]
 [33.88800315]
 [28.28358539]
 [20.99906918]
 [30.71792812]
 [33.27589

creste the sales of item using a balanced equation

In [23]:
noise = np.random.normal(0, 15, 150).reshape(-1,1)
sales_mod = (
    200
    +6*temp
    -0.8*price
    -0.6*humidity
    +noise
)
sales_mod = np.clip(sales_mod, 0, None)


In [6]:
print(sales_mod)

[[239.18253616]
 [163.23088329]
 [280.92567641]
 [188.92912499]
 [290.31005439]
 [308.08324472]
 [206.2200576 ]
 [195.6637071 ]
 [334.79900733]
 [186.57468062]
 [264.36484763]
 [135.45614849]
 [231.11876657]
 [184.05153026]
 [218.44034002]
 [178.9533934 ]
 [211.50796099]
 [133.23213659]
 [204.74770721]
 [195.29144026]
 [194.78392168]
 [304.77536293]
 [301.93502852]
 [248.64215829]
 [163.48965386]
 [257.41141329]
 [239.02363485]
 [ 91.86104409]
 [267.00075525]
 [212.67356307]
 [220.48991696]
 [197.36447743]
 [258.51446326]
 [214.73907713]
 [317.64920761]
 [208.68601286]
 [ 87.98229514]
 [329.5936064 ]
 [194.51024326]
 [191.55362378]
 [238.43618346]
 [175.66713178]
 [286.43148202]
 [159.14698506]
 [248.8746576 ]
 [254.6953644 ]
 [290.28723112]
 [270.83147415]
 [280.75226172]
 [270.65451361]
 [225.9056534 ]
 [287.09785234]
 [137.74536229]
 [186.67869748]
 [132.34031648]
 [143.00262652]
 [241.8565064 ]
 [362.73011455]
 [289.71365091]
 [126.44012753]
 [237.65676366]
 [299.9878764 ]
 [207.40

In [7]:
print(f"temp = {temp} \n humidity= {humidity} \n price={price}")

temp = [[26.74413151]
 [22.8568393 ]
 [33.84147294]
 [24.12504228]
 [27.83718746]
 [37.91349555]
 [24.08632767]
 [30.15610128]
 [28.38543322]
 [20.36248082]
 [35.85516227]
 [21.38091813]
 [29.48510042]
 [31.2135659 ]
 [32.56852913]
 [33.77263259]
 [25.06544767]
 [20.19957553]
 [34.46887325]
 [30.71313199]
 [36.72235406]
 [36.42776726]
 [36.86652336]
 [29.7018932 ]
 [26.67256792]
 [35.83116405]
 [29.02588226]
 [23.66884393]
 [37.09948039]
 [37.65119754]
 [29.32619512]
 [21.51399455]
 [27.7565218 ]
 [36.07075319]
 [38.03548057]
 [24.06945485]
 [21.33947224]
 [37.54700906]
 [27.78809878]
 [30.83521929]
 [39.36131624]
 [21.33129456]
 [32.96636015]
 [21.48210845]
 [27.50937857]
 [36.0762909 ]
 [28.66944466]
 [39.94364708]
 [31.1811857 ]
 [26.42324305]
 [24.40222652]
 [27.01041069]
 [27.45066548]
 [21.37427355]
 [27.39148399]
 [29.28477039]
 [34.45475504]
 [33.13458969]
 [34.1753131 ]
 [20.16727364]
 [24.35334799]
 [33.23368577]
 [29.67978736]
 [20.10626951]
 [36.08989285]
 [35.45619147]
 [3

In [8]:
X=np.hstack((temp,humidity,price))

In [9]:
ones=np.ones((X.shape[0],1))

In [10]:

X_b = np.hstack((ones,X))

In [11]:
X_b_T=X_b.T

In [12]:
B=np.linalg.inv((X_b_T@X_b))@(X_b_T@sales_mod)

In [13]:
print(B)

[[205.14330342]
 [  5.9406765 ]
 [ -0.54914927]
 [ -0.84779695]]


In [14]:
np.random.seed(42)
temp_test=np.random.uniform(20,40,30).reshape(-1,1)
humidity_test=np.random.uniform(0,100,30).reshape(-1,1)
price_test=np.random.uniform(50,250,30).reshape(-1,1)


In [15]:
noise_test = np.random.normal(0, 15, 30).reshape(-1,1)

sales_test = (
    200
    + 6 * temp_test
    - 0.8 * price_test
    - 0.6 * humidity_test
    + noise_test
)

In [16]:
sales_pred= (B[0]+B[1]*temp_test+B[2]*humidity_test+B[3]*price_test)

In [17]:
from sklearn.metrics import root_mean_squared_error

In [18]:
RMSE=root_mean_squared_error(sales_test,sales_pred)

In [19]:
print(RMSE)

14.47376649830107
